### ISSUE TITLE
Occasionally stops showing time and web interface not responding

### ISSUE THREAD

**Issue by MennoLabs** [judge2005/EleksTubeIPS#19]
Sometimes the clock stops for 30 - 90 seconds.
It will stand still, eventually jump to the current time.
Web interface also not available at those moments.
Can't ping the clock either.

**Comment by judge2005** [comment]
This is most likely because of Wi-Fi issues - the placement of the ESP32 module in the clock is not great from a radio perspective, which can make the Wi-Fi connection susceptible to interference. A friend had this when he was charging his phone next to the clock for example. Another possibility is that the power adapter it is plugged in to is not providing enough power, so try a different one.

**Comment by MennoLabs** [comment]
I guess with WiFi enabled the power requirements have gone up considerably compared to the original firmware.
It is now connected to a max 0,5A power supply.
A bit of Googling digs up:
"It has also been observed that the chip draws more than 790 mA at times, particularly when both WiFi and Bluetooth are used simultaneously."
Will find a beefier power supply and try that.
Thanks!
